win11:
	g++.exe -fdiagnostics-color=always -I./include ./src/window.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

win12:
	g++.exe -fdiagnostics-color=always -I./include ./src/make_window.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

win21:
	g++.exe -fdiagnostics-color=always -I./include ./src/triangle.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe


win22:
	g++.exe -fdiagnostics-color=always -I./include ./src/triangle_indexed.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

win23:
	g++.exe -fdiagnostics-color=always -I./include ./src/triangle_exercise_1.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

win24:
	g++.exe -fdiagnostics-color=always -I./include ./src/triangle_exer_2.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

win25:
	g++.exe -fdiagnostics-color=always -I./include ./src/triangle_exercise_3.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe


linux:
	g++ -fdiagnostics-color=always -I./include ./src/main.cpp ./src/glad.c -o ./build/main -Llib -lglfw -lGL -lXrandr -lX11 -lrt -ldl
	./build/main